version: '3.3'
services:

  db:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always

  java:
    build:
      context: ./
      dockerfile: ./Javafile
    restart: always
    ports:
      - "8080:8080"